travis:
  secure:
    BINSTAR_TOKEN: Zb15xWOdmdtqWjHmFcgtEKqykwPVigzO7hGKxrtMJ+yl2AHEvW7rduBFRichHHKfD8FTkLHpJv5ZoyXNkCrtGARvaabUHFrAyub7Aq9h+sop2blDteEa/4hi+FMo/l5zPAbJla0abyg19lXercTPzQSODwoiP5mr0iV8l5AiL4OILBK+pOtZ6U8h1ei1oy7nZRDcGE9+hs/yoX2tMzOfkl9b3qNSuvfeqxhjGkCa7aMozev9Bc1Y9JPYf21axVEne4qD51CddBLKRMOz+olDO8X58es+dXpuuNguDVH+p2CYH+tH+yXHHL+F00GDeZy4nq+VP2rJiE0oMc9zJACy0KN/GIxd4B1/MhDeJT79Dvho7UiI36Pf5mHOYlw7Q6oC3w9RtP9NwV9lS8VAvGfd1ZQ9hSzLoR81aTrrnQOJhmYoCw5Vp92QCEI/J0MVT+NgAgNs4ElU/0ervbeHw9WTfapcgUQrt9ZGUGdVYi8BOW1gYisKwiYomzQUOqSnZf6H8MGadDZ4bbFSvUtstuN/TH9CW8+vKjeXjI2/uyfmD4k/bMeECb+OSz9qupU2aaHdL+dD+HHG+2DpESoCBFjkzxoVrVtAX3glbrMarPm+WGaWGxKtueYm+fv6cyDuSwikp82F1mK9NmID8AohmGUYO7IYt40C6vybMv6ShZaGuwI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
